### ISSUE TITLE
Using Gradle is causing 401: Unauthorized

### ISSUE THREAD

**Issue by muelleel** [untisapi/untis4j#15]
Hey,
Specifically - new Maintainer @maxmielchen 

When using the provided snippets for using the Libary the remote Server does respond with 401:

`Could not GET 'https://maven.pkg.github.com/ByteDream/untis4j/org/bytedream/untis4j/1.3.1/untis4j-1.3.1.pom'. Received status code 401 from server: Unauthorized`

![grafik](https://user-images.githubusercontent.com/40674502/215155110-aacd6081-d91c-4bc5-8343-2892f67f9aa2.png)

Any Ideas on this? I think this should be publicly available without authorization...

**Comment by maxmielchen** [comment]
Unfortunately, for the time being, there will be no official way to access this package. Temporary we can get the package like this:

## Installation: 

### Maven

Add the GitHub repository to your build file
```XML
<repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
</repository>
```

Add the dependency
```XML
<dependency>
       <groupId>com.github.untisapi</groupId>
       <artifactId>untis4j</artifactId>
       <version>jitpack-SNAPSHOT</version>
</dependency>
```

### Groovy

Add the GitHub repository to your build file
```groovy
maven { url 'https://jitpack.io' }
```

Add the dependency
```groovy
implementation 'com.github.untisapi:untis4j:jitpack-SNAPSHOT'
```

### Kotlin

Add the GitHub repository to your build file
```kotlin
maven { url='https://jitpack.io' }
```

Add the dependency
```kotlin
implementation ("com.github.untisapi:untis4j:jitpack-SNAPSHOT")
```

**Comment by muelleel** [comment]
Yeah that worked!

Thanks
